service: Vanilla
frameworkVersion: ^3
useDotenv: true

package:
  individually: true
  patterns:
    - '!.env'

provider:
  name: aws
  region: ap-southeast-2
  stage: v1
  profile: ${env:AWS_PROFILE, 'default'}

resources:
  Resources:
    LineEmailParameter:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /vanilla/line/email
        Type: String
        Value: ${env:LINE_EMAIL}

    LinePasswordParameter:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /vanilla/line/password
        Type: String
        Value: ${env:LINE_PASSWORD}

    OpenAIApiKeyParameter:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /vanilla/openai/apiKey
        Type: String
        Value: ${env:DEEPSEEK_API_KEY}

    TavilyApiKeyParameter:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /vanilla/tavily/apiKey
        Type: String
        Value: ${env:TAVILY_API_KEY}

    MessageTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Message
        AttributeDefinitions:
          - AttributeName: thread_id
            AttributeType: S
          - AttributeName: created_at
            AttributeType: N
        KeySchema:
          - AttributeName: thread_id
            KeyType: HASH
          - AttributeName: created_at
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    ThreadTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Thread
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
